spring:
  datasource:
    url: jdbc:mysql://localhost:3306/borad
    username: root
    password: "kfcayo123"
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: auto
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
